services:
  plateau.snap.server:
    image: ${DOCKER_REGISTRY-}plateau-snap-server:latest
    ports:
      - "80:8080"
      - "443:8081"
    restart: always
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - SECRET_NAME=${SECRET_NAME}
